name: build-linux-executable
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build single executable
        run: |
          # On inclut le dossier templates créé par app.py
          pyinstaller --onefile --name Cafeteria app.py \
            --add-data "templates:templates"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Cafeteria-linux
          path: dist/Cafeteria
